CREATE SCHEMA IF NOT EXISTS learning;
SET NAMES 'UTF8MB4';
SET TIME_ZONE = '+5:30';
USE learning;
DROP TABLE IF EXISTS users;
CREATE TABLE users
(
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   first_name VARCHAR (50) NOT NULL,
   last_name VARCHAR (50) NOT NULL,
   email VARCHAR (100) NOT NULL,
   password VARCHAR (255) DEFAULT NULL,
   address VARCHAR (255) DEFAULT NULL,
   phone VARCHAR (20) DEFAULT NULL,
   title VARCHAR (30) DEFAULT NULL,
   bio VARCHAR (255) DEFAULT NULL,
   enabled BOOLEAN DEFAULT FALSE,
   not_locked BOOLEAN DEFAULT TRUE,
   using_mfa BOOLEAN DEFAULT FALSE,
   created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
   image_url VARCHAR (255) DEFAULT 'https://cdn-icons-png.flaticon.com/512/149/149071.png',
   CONSTRAINT UQ_Users_Email UNIQUE (email)
);
DROP TABLE IF EXISTS roles;
CREATE TABLE roles
(
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR (50) NOT NULL,
   permission VARCHAR (255) NOT NULL,
   CONSTRAINT UQ_Roles_name UNIQUE (name)
);
DROP TABLE IF EXISTS permissions;
CREATE TABLE permissions
(
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR (50) NOT NULL CHECK
   (
      name IN
      (
         'USER:READ',
         'USER:UPDATE',
         'USER:DELETE',
         'CUSTOMER:READ',
         'CUSTOMER:UPDATE',
         'CUSTOMER:DELETE'
      )
   ),
   CONSTRAINT UQ_Permissions_name UNIQUE (name)
);
DROP TABLE IF EXISTS role_permissions;
CREATE TABLE role_permissions
(
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   role_id BIGINT UNSIGNED NOT NULL,
   permission_id BIGINT UNSIGNED NOT NULL,
   FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE ON UPDATE CASCADE,
   FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
DROP TABLE IF EXISTS user_roles;
CREATE TABLE user_roles
(
   id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   role_id BIGINT UNSIGNED NOT NULL,
   user_id BIGINT UNSIGNED NOT NULL,
   FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT ON UPDATE CASCADE,
   FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
   CONSTRAINT UQ_UserRoles_User_Id UNIQUE (user_id)
);